version: '3.4'
services:
  typesense:
    image: typesense/typesense:0.25.2
    restart: on-failure
    ports:
      - "8108:8108"
    volumes:
      - ./typesense-data:/data
    command: '--data-dir /data --api-key=xyz --enable-cors'
  app:
    build: ./
    ports:
      - "8501:8501"
    depends_on:
      - typesense
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=test123
      - POSTGRES_DB=document_meta
      - POSTGRES_DB_PORT=5432
    ports:
      - 6543:5432
volumes:
  postgres_data:
